// AUTO-GENERATED from schemas. DO NOT EDIT.

/**
 * Feature payload generated by the safety gate / acuity ensemble prior to triage prioritisation.
 */
export interface AcuitySignalFeatures {
  /**
   * Semantic version of this payload.
   */
  schemaVersion: string;
  /**
   * Timestamp when the signal was computed (UTC).
   */
  generatedAt: string;
  /**
   * Version identifier of the model producing the scores.
   */
  modelVersion?: string;
  /**
   * Argmax decision from the acuity classifier.
   */
  predictedClass?: "emergency" | "urgent" | "routine";
  /**
   * Probability of the emergency class.
   */
  emergencyProbability?: number;
  /**
   * Probability of the urgent class.
   */
  urgentProbability?: number;
  /**
   * Probability of the routine class.
   */
  routineProbability?: number;
  /**
   * Fixed-length embedding derived from symptom/document encoding.
   *
   * @minItems 1
   * @maxItems 512
   */
  symptomEmbedding?: [number, ...number[]];
  /**
   * Patient age in years at the time the feature vector was generated.
   */
  patientAgeYears?: number;
  /**
   * Map of comorbidity indicators used by the model. Keys follow snake_case ICD topic names.
   */
  comorbidityFlags?: {
    [k: string]: boolean;
  };
  /**
   * Model interpretability artefacts (e.g., SHAP style contributions).
   *
   * @maxItems 32
   */
  explanations?: {
    /**
     * Feature name or token.
     */
    feature: string;
    /**
     * Signed contribution toward the emergency decision.
     */
    contribution: number;
  }[];
  /**
   * Optional expiry timestamp (UTC) after which the signal must be recomputed.
   */
  expiresAt?: string;
}
